wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1630371632
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      4: 3.8.5
      5: 0.12.1
      8:
      - 5
batch_size:
  desc: null
  value: 128
cutface:
  desc: null
  value: true
epoch:
  desc: null
  value: 50
label:
  desc: null
  value: age
loss:
  desc: null
  value: LabelSmoothingLoss
lr:
  desc: null
  value: 0.005
name:
  desc: null
  value: multi_augmentation_age_label_smoothing
optimizer:
  desc: null
  value: SGD
pretrained_model:
  desc: null
  value: efficientnet_b4
